name: Monitor

on:
  # Kích hoạt khi có push lên các nhánh cụ thể
  push:
  # Kích hoạt tự động theo lịch trình
  schedule:
    - cron: '*/5 * * * *' # Chạy mỗi 15 phút
  # Cho phép chạy thủ công

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://flightdotapi.azurewebsites.net/health"
        expected-statuses: "200"
