name: Monitor Application

on:
  schedule:
    - cron: '*/1 * * * *'  # Chạy mỗi 1 phút (cron syntax)
env:
  HEALTH_CHECK_URL: 'https://flightdotapi.azurewebsites.net/health' # URL kiểm tra sức khỏe


jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check API Health
        run: |
          echo "Checking health at ${{ env.HEALTH_CHECK_URL }}"
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.HEALTH_CHECK_URL }})
          if [ "$response" -eq 200 ]; then
            echo "Health check passed!"
          else
            echo "Health check failed!"
            exit 1
          fi
